name: CI

on: [push, pull_request]

env:
  HEAPS_VER: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      # we are using this version in order to build vscode-textmate
      - name: Setup Node
        uses: actions/setup-node@v1

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.4

      - name: Install
        # at some point all npm needs to be in package.json
        run: |
          npm install
          npm install -g uglify-js
          npm install -g less@2.7
          npm install -g less-plugin-clean-css@1.5
          haxelib install all --always
          haxelib git heaps https://github.com/heapsio/heaps
          haxelib list

      - name: Script
        run: |
          haxe build-run-dox.hxml
          haxe build-samples.hxml
          haxe get-wiki.hxml
          haxe heaps.io.hxml

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./output

  deploy:
    if: github.ref == 'refs/heads/master'
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v4
